---

- block:
    - name: Set our download path
      set_fact:
          download_path: "{{ [ artefact.dest_path, artefact.name ]|join('/') }}"
  when: artefact.dest_path|default(false)

- block:
    - name: Set our download path
      set_fact:
          download_path: "{{ [mount_point, 'software',  artefact.name]|join('/')  }}"
  when: artefact.dest_path|default(false) == false

- name: Print out our download path
  debug:
    msg: "{{ download_path }}"

- name: Get our packages from S3
  aws_s3:
    bucket: "{{ wl_artefact_bucket }}"
    object: "/{{ artefact_path }}/{{ artefact.name }}"
    dest: "{{ download_path }}"
    mode: get

- name: Configure our owner and permissions
  file:
    path: "{{ artefact.dest_path|default(mount_point + '/software/' + artefact.name) }}"
    mode: "{{ artefact.mode|default('0775') }}"
    owner: "{{ artefact.owner|default(rdbms_service_user.name) }}"
    group:  "{{ artefact.group|default(rdbms_service_user.group) }}"
    recurse: true

- name: List our downloads path
  command: "ls -ltr {{ download_path }}"


