---

- name: Get our software
  include: download-artefacts.yml
  with_items:
    - "{{ oracledb_artefacts  + oracledb_patches }}"
  loop_control:
    loop_var: artefact

- name: Unpack main software
  unarchive:
    src: "{{ mount_point }}/software/{{ item.name }}"
    dest: "{{ mount_point }}/software/11gR"
    remote_src: yes
  become: yes
  become_user: "{{ rdbms_service_user.name }}"
  with_items:
    - "{{ oracledb_artefacts[:3] }}"

- name: Unpack our patches
  unarchive:
    src: "{{ mount_point }}/software/{{ item.name }}"
    dest: "{{ mount_point }}/software/11gR/patches"
    remote_src: yes
  become: yes
  become_user: "{{ rdbms_service_user.name }}"
  with_items:
    - "{{ oracledb_patches }}"

- name: Remove our zips
  file:
    path: "{{ mount_point }}/software/{{ item.name }}"
    state: absent
  with_items:
    - "{{ oracledb_artefacts[:3] + oracledb_patches }}"
