---

- name: Get our software 
  include: download-artefacts.yml
  with_items:
    - "{{ oracledb_artefacts  + oracledb_patches + oracledb_post_patches + oracledb_rpms + oracledb_osbws }} + {{ oraclegrid_artefacts | default([]) }} + {{ oraclegrid_patches | default([]) }}"
  loop_control:
    loop_var: artefact

- name: Install our rpms
  yum:
    name: "{{ item.dest|default(mount_point + '/software/' + item.name) }}"
    state: present
  with_items: "{{ oracledb_rpms }}"

- name: Unpack software
  include: unpack-software.yml

- name: Install Oracle Grid with defaults in template
  include: install-grid.yml

- name: Install Oracle DB software
  include: install-database.yml

- name: Remove our downloaded archives
  file:
    path: "{{ artefact.dest|default( mount_point + '/software/' + artefact.name) }}"
    state: absent
  become: true
  ignore_errors: true
  with_items:
    - "{{ artifacts_to_clean|default(oracledb_artefacts + oracledb_patches + oracledb_rpms + oracledb_osbws) }} + {{ oraclegrid_artefacts | default([]) }} + {{ oraclegrid_patches | default([]) }}"
  loop_control:
    loop_var: artefact

- name: Create database version hidden file for bootstapping phase
  lineinfile:
    create: yes
    path: "~/.db_version"
    line: "{{ db_version }}"
  when: (db_version is defined) and (db_version == '11g' or db_version == '18c' or db_version == '19c')
