---

- name: preparing database installation template
  template:
    src: "{{ role_path}}/templates/{{ oracle_database_response_file }}.rsp.j2"
    dest: "/tmp/{{ oracle_database_response_file }}.rsp"
    owner: "{{ rdbms_service_user.name }}"
    group: "{{ rdbms_service_user.group }}"

- name: Oracle 11g Database Installation
  include: install-11g-database.yml
  when: db_version is not defined or (db_version is defined and db_version == '11g')

- name: Oracle 18c Database Installation
  include: install-18c-database.yml
  when: (db_version is defined) and (db_version == '18c')

- name: run post-installation scripts as root
  shell: "{{ item }}"
  become: yes
  become_user: root
  with_items:
    - "{{ oracle_database_inventory_location }}/orainstRoot.sh"
    - "{{ oracle_database_oracle_home }}/root.sh"
  register: root_result
  failed_when: root_result.stderr_lines == ""
