---

- name: Get our software
  include: download-artefacts.yml
  with_items:
    - "{{ oracledb_artefacts  + oracledb_patches + oracledb_rpms }}"
  loop_control:
    loop_var: artefact

- name: Install our rpms
  yum:
    name: "{{ item.dest|default(mount_point + '/software/' + item.name) }}"
    state: present
  with_items: "{{ oracledb_rpms }}"

- name: Unpack main software
  unarchive:
    src: "{{ mount_point }}/software/{{ item.name }}"
    dest: "{{ mount_point }}/software/11gR"
    remote_src: yes
  become: yes
  become_user: "{{ rdbms_service_user.name }}"
  with_items:
    - "{{ oracledb_artefacts }}"

- name: Unpack our patches
  unarchive:
    src: "{{ mount_point }}/software/{{ item.name }}"
    dest: "{{ mount_point }}/software/11gR/patches"
    remote_src: yes
  become: yes
  become_user: "{{ rdbms_service_user.name }}"
  with_items:
    - "{{ oracledb_patches }}"

- name: Install Oracle Grid with defaults in template
  include: install-grid.yml

- name: Install Oracle DB software
  include: install-database.yml

- name: Remove our downloaded archives
  file:
    path: "{{ mount_point }}/software/{{ item.name }}"
    state: absent
  with_items:
    - "{{ oracledb_artefacts + oracledb_patches + oracledb_rpms }}"
