---

- name: Load in our vars
  include_vars:
    file: main.yml
    name: weblogic_vars

- name: Create base directory structure
  include: create-directories.yml
  vars:
    - rdbms_service_user: "{{ system_users[0] }}"

- name: Prepare our OS for the imminent arrival of OracleDB
  include: update-os-params.yml
